### ISSUE TITLE
Add support for resources arrays to offload test suite

### ISSUE THREAD

**Issue by hekota** [llvm/wg-hlsl#291]
The offload test suite currently supports mapping of individual resources like this:

```
RWBuffer<float4> In : register(u0, space0);
```
yaml:
```
Buffers:
  - Name: In
    Format: Float32
    Channels: 4
    Data: [ 2, 4, 6, 8]
...
```
This task involves designing and implementing support for resource arrays within the offload test suite. This includes defining how array dimensions and data are specified in the YAML test configuration, how this information is propagated to the runtime, and how it is validated in test outputs. The implementation must support multi-dimensional and unbounded arrays.

```
RWBuffer<float4> Array1[10] : register(u0);
RWBuffer<float4> Array2[10][5] : register(u10);
RWBuffer<float4> Array3[] : register(u0, space1);
```
